version: '2'
services:
  mongo:
    image: "mongo"
    container_name: mongo_container
    ports:
      - "27017:27017"
    network_mode: bridge

  flask:
    build:
      context: ./flask_bdgest/
      dockerfile: Dockerfile
    image: flask_image
    container_name: flask_container
    ports:
      - "1000:1000"
    network_mode: bridge

  scrapy:
    build:
      context: ./scrapy_bdgest/
      dockerfile: Dockerfile
    image: scrapy_image
    container_name: scrapy_container
    network_mode: bridge
